"""Build an offline manual-review form; keep predictions separate."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
report = json.loads((ROOT / 'artifacts/external_image_test_20261008_170246/results.json').read_text())
order = ['4416e128','8d412fd2','804bf259','78290525','e04e93b9','be5a59e0','1361f8a9','3abf7f37','6ea1ba72','0fdb5afd','4afc1db6','70271e27']
rows = sorted(report['results'], key=lambda r: order.index(r['file'].split('_')[-1].split('.')[0]))
page = '''<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>外部照片｜人工補資料</title>
<style>*{box-sizing:border-box}body{margin:0;background:#eff3f6;color:#203747;font:16px system-ui}header{padding:30px max(20px,calc((100% - 1100px)/2));background:#173c48;color:white}h1{margin:0 0 12px}p{line-height:1.6}.bar{position:sticky;top:0;background:#fff;padding:14px;box-shadow:0 2px 10px #0001;z-index:2;display:flex;gap:12px;align-items:center;flex-wrap:wrap}button,.import{border:0;background:#176b70;color:white;padding:12px 18px;border-radius:9px;cursor:pointer;font:inherit}main{max-width:1100px;margin:24px auto;padding:0 16px;display:grid;gap:24px}article{background:white;border-radius:16px;padding:24px;display:grid;grid-template-columns:1fr 1fr;gap:24px}img{width:100%;height:440px;object-fit:contain;background:#f4f5f6;border-radius:10px}label{display:block;margin:12px 0 5px}select,input[type=text],textarea{display:block;width:100%;padding:10px;border:1px solid #bbcbd0;border-radius:8px;font:inherit}textarea{min-height:85px}small{color:#637780}details{margin-top:20px;padding:12px;background:#f2f5f7}a{color:#176b70}@media(max-width:700px){article{grid-template-columns:1fr}img{height:320px}}</style>
<header><h1>外部照片 · 人工補資料</h1><p>12 張待核對照片。請填你真正看得出的內容；不清楚就選「無法判斷」。<br>這不是模型答案，也不能單靠照片確認出廠原因或真實訂單。</p></header>
<div class="bar"><button id="export">下載補資料 JSON</button><label class="import">匯入繼續填寫<input id="import" type="file" accept=".json" hidden></label><strong id="count"></strong><small>離開前請下載保存；本頁不會傳送資料。</small></div><main id="cards"></main>
<script>
const source=DATA;const fields=['defect','category','location','description','source_url','note'];
const options={'':'尚未填寫',hole_or_tear:'破洞／撕裂',stain_or_spot:'污漬／斑點',discoloration:'褪色／變色（不確定是否污漬）',both:'同時有破洞與污漬',no_visible_defect:'看不到明顯缺陷',uncertain:'無法判斷／可能是印花'};
let rows=source.map(r=>({file:r.file,sha256:r.sha256,defect:'',category:'',location:'',description:'',source_url:'',note:'',confirmed:false}));
function count(){document.querySelector('#count').textContent=`已確認 ${rows.filter(r=>r.confirmed).length} / ${rows.length}`}
function render(){const cards=document.querySelector('#cards');cards.replaceChildren();rows.forEach((r,i)=>{const card=document.createElement('article');const left=document.createElement('div');const h=document.createElement('h2');h.textContent=i===0?'上一張：雙洞近照':`照片 ${i}`;const img=document.createElement('img');img.src='data/external_test_pending/'+r.file;const link=document.createElement('a');link.href=img.src;link.target='_blank';link.textContent='開啟原圖放大';left.append(h,img,link);const right=document.createElement('div');const check=document.createElement('input');check.type='checkbox';check.checked=r.confirmed;
function change(key,value){r[key]=value;r.confirmed=false;check.checked=false;count()}
for(const [key,title] of Object.entries({defect:'你觀察到的缺陷（必填）',category:'衣服種類（不知道可填未知）',location:'缺陷位置（例如：前胸；不確定可填未知）',description:'你想測試的顧客描述（英文，可留空）',source_url:'圖片來源網址／自己拍攝（可留空）',note:'備註／不確定的原因'})){const label=document.createElement('label');label.textContent=title;let input;if(key==='defect'){input=document.createElement('select');for(const [v,t] of Object.entries(options))input.add(new Option(t,v))}else{input=document.createElement(key==='description'||key==='note'?'textarea':'input');if(input.tagName==='INPUT')input.type='text'}input.value=r[key];input.oninput=()=>change(key,input.value);right.append(label,input)}
const label=document.createElement('label');label.append(check,document.createTextNode(' 我已逐張查看並確認上述資料'));check.onchange=()=>{if(check.checked&&!r.defect){alert('請先選缺陷類別，無法判斷也可以。');check.checked=false}r.confirmed=check.checked;count()};right.append(label);const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='填完後再看：模型預測（不是人工答案）';const p=document.createElement('p');p.textContent=source[i].prediction+' · 分數 '+source[i].score.toFixed(3)+'（不是準確率）';details.append(summary,p);right.append(details);card.append(left,right);cards.append(card)});count()}
document.querySelector('#export').onclick=()=>{const blob=new Blob([JSON.stringify({schema_version:1,review_method:'user_visual_review',created_at:new Date().toISOString(),cases:rows},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='external_photo_human_review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.querySelector('#import').onchange=async e=>{try{if(!e.target.files[0])return;const data=JSON.parse(await e.target.files[0].text());if(data.schema_version!==1||!Array.isArray(data.cases))throw Error('格式不符');const next=rows.map(r=>({...r}));const seen=new Set();for(const v of data.cases){const r=next.find(x=>x.file===v.file&&x.sha256===v.sha256);if(!r||seen.has(v.file)||!Object.hasOwn(options,v.defect)||fields.some(k=>typeof v[k]!=='string')||typeof v.confirmed!=='boolean'||(v.confirmed&&!v.defect))throw Error('圖片或欄位不符');seen.add(v.file);for(const k of fields)r[k]=v[k];r.confirmed=v.confirmed}rows=next;render()}catch(err){alert('匯入失敗：'+err.message)}};window.addEventListener('beforeunload',e=>{if(rows.some(r=>r.defect||r.note)){e.preventDefault();e.returnValue=''}});render();
</script></html>'''
output = ROOT / 'external_photo_review.html'
output.write_text(page.replace('DATA', json.dumps(rows, ensure_ascii=False).replace('<', '\\u003c')), encoding='utf-8')
print(output)
